samsung: add missing dependencies, liblog
hardware/samsung/ril/libsecril-client/secril-client.cpp:355: error: undefined reference to '__android_log_buf_print'
hardware/samsung/ril/libsecril-client/secril-client.cpp:366: error: undefined reference to '__android_log_buf_print'
hardware/samsung/ril/libsecril-client/secril-client.cpp:381: error: undefined reference to '__android_log_buf_print'
hardware/samsung/ril/libsecril-client/secril-client.cpp:1265: error: undefined reference to '__android_log_buf_print'